 # syntax=docker/dockerfile:1.4
FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# Install required tools including 'make'
RUN apk update && apk add --no-cache \
    make=4.4.1-r2 \
    gcc=13.2.1_git20240309-r0 \
    musl-dev=1.2.5-r0 \
    libffi-dev=3.4.6-r0

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py docker/boot.sh Makefile ./

# Install dependencies
RUN <<-EOF
    python -m venv .venv
    .venv/bin/pip3 install -r requirements.txt
EOF

# Set up the production environment
ENV FLASK_APP microblog.py

# Set up permissions
RUN <<-EOF
    chmod +x boot.sh
    chown -R microblog:microblog ./
EOF

# Run as the microblog user
USER microblog

# Expose port 5000
EXPOSE 5000

# Run the boot script
ENTRYPOINT ["./boot.sh"]
