name: Run Tests

on:
  push:
    branches:
      - main # Trigger on push to the main branch (or specify other branches as needed)
  pull_request:
    branches:
      - main # Trigger on pull request targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest # You can adjust this to use other runners if needed

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment (optional if Python isn't pre-installed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8" # Adjust Python version if needed

      # Step 3: Install dependencies
      - name: Install dependencies from requirements/test.txt
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements/test.txt

      # Step 4: Run tests using 'make test'
      - name: Run tests
        run: |
          . venv/bin/activate  # Activate virtual environment
          make test            # Run tests via Makefile
